/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tagityokalu;

import java.awt.GridBagConstraints;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JLabel;

/**
 *
 * @author janne
 */
public class TietoPaneli extends javax.swing.JPanel {

    private String idArvo;
    
    /**
     * Creates new form TietoPaneli
     */
    public TietoPaneli() {
        initComponents();
    }
    
    public String getId()
    {
        return idArvo;
    }
    
    public void addData(HashMap<String,String> data, String id)
    {
        idArvo = data.get(id);
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;
        c.anchor = GridBagConstraints.LINE_START;
        c.ipadx = 20;
        //haetaan datamapin avaimet
        Set<String> tmpAvaimet = data.keySet();
        String[] avaimet = tmpAvaimet.toArray(new String[tmpAvaimet.size()]);
        int i = 0;
        for(String avain : avaimet)
        {
            //lisätään sille labeli ja arvo kentät
            
            c.gridx = 0;
            c.gridy = i;
            this.add(new JLabel(avain),c);
            c.gridx = 1;
            c.gridy = i;
            this.add(new JLabel(data.get(avain)),c);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
